### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by seripap** [seripap/vainglory#1]
TODO for a stable v1

- [x] Add data models; getters and setters
- [x] Better deserialization of JSON API
- [x] Better Query formatting
- [x] Collection modeling
- [x] Parsing / formatting time
- [x] Region support
- [ ] Tests, Coverage over 75%
- [x] Better examples

**Comment by vaincoach** [comment]
Awesome library - very helpful. Version 0.9.1 works for me, but updating to 0.9.2 gives me this: `Error: Cannot find module 'vainglory'`. I get this even when creating an empty project with only the vainglory dependency.

**Comment by seripap** [comment]
@vaincoach sorry about that- pull down v0.9.4 and it should resolve. thanks for the report!

**Comment by vaincoach** [comment]
Works perfectly now on v0.9.4 - thanks for your help.

**Comment by hineltjar** [comment]
Great library!

> region [String] - Use: na (North America), sg (SEA), eu (Europe)
> https://github.com/seripap/vainglory/blob/master/README.md

Is this library also compatible with EA Region?
