### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by PierreAndreis** [seripap/vainglory#24]
There should be a changelog

**Comment by PierreAndreis** [comment]
and https://github.com/seripap/vainglory/commit/48311f51819201ca64777c8bfd7389802eca8b11 should be added to Releases notes as well, as it is a breaking change

**Comment by seripap** [comment]
I added a CHANGELOG.md, which is just an aggregate of whatever is in [Releases](https://github.com/seripap/vainglory/releases). Going forward, I will do better at highlighting breaking changes.
