### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by hineltjar** [seripap/vainglory#3]
When running with `localhost:3000`, the following error appears.
How can I fix with it?

```
XMLHttpRequest cannot load https://api.dc01.gamelockerapp.com/shards/ea/players?filter[playerName]=xxxx. Request header field content-encoding is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by seripap** [comment]
This client is not meant to be ran in the browser, you'd want to proxy your own requests through it using something like express or standard http modules

**Comment by hineltjar** [comment]
I understood. Thank you for the answer.
