### ISSUE TITLE
nom install error

### ISSUE THREAD

**Issue by daftunes** [seripap/vainglory#4]
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "vainglory" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ENOSELF

npm ERR! Refusing to install vainglory as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by seripap** [comment]
What version node are you using?

**Comment by daftunes** [comment]
the version is
npm info using npm@3.10.8
npm info using node@v6.9.1

now I see those messages when install vainglory to node module
└─┬ vainglory@0.7.4
  ├── UNMET PEER DEPENDENCY eslint@^3.15.0
  ├─┬ eslint-config-airbnb@14.1.0
  │ ├── UNMET PEER DEPENDENCY eslint@^3.16.1
  │ ├── eslint-config-airbnb-base@11.1.1
  │ └── UNMET PEER DEPENDENCY eslint-plugin-import@^2.2.0
  ├── UNMET PEER DEPENDENCY eslint-plugin-import@^2.2.0
  ├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^3.0.2 || ^4.0.0
  └── UNMET PEER DEPENDENCY eslint-plugin-react@^6.9.0

**Comment by seripap** [comment]
you're running an outdated version. try this

```
npm install vainglory@v0.9.7
```
