### ISSUE TITLE
Add telemetry support

### ISSUE THREAD

**Issue by nathancarter** [seripap/vainglory#8]
Right now the `parser.js` file [removes](https://github.com/seripap/vainglory/blob/master/src/api/parser.js#L40) the `included` data from the match, which contains all the information about where to fetch the telemetry from an online URL.  Please do not discard that information, so that the final match that the Vainglory JS API returns contains the telemetry information.  Thanks!

**Comment by seripap** [comment]
I've added support for telemetry data with v1.0.0- it **_should_** work [out of the box](https://github.com/seripap/vainglory#telemetry). Let me know if that works for you 👍

**Comment by nathancarter** [comment]
Just tested -- works great, thank you for the super-fast turnaround time!

**Comment by seripap** [comment]
Also just updated (v1.0.1) with a `.resolve()` helper that will return the data that is associated with the data URL.

```javascript
const matchId = 'f5373c40-0aa9-11e7-bcff-0667892d829e';
vainglory.matches.single(matchId).then(async (match) => {
  const telemetry = await match.assets[0].resolve();
  console.log(telemetry);
}).catch((err) => console.error(err));
```

 👍

**Comment by nathancarter** [comment]
Without `await`, is that just `match.assets[0].resolve((telemetry) => doStuff(telemetry));`?

**Comment by seripap** [comment]
it's just a promise, so something like;

```javascript
match.assets[0].resolve().then(telemetry => doStuff(telemetry));
```

**Comment by nathancarter** [comment]
Ah, right, thanks!
